name: performance checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  performance-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: "@university-of-york"
          always-auth: true

      - name: Install application dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build the application
        run: npm run build

      - name: Run the application in the background
        run: (npm start &)

      - name: Wait for the application to start
        run: sleep 10

      - name: Check Lighthouse performance score
        uses: university-of-york/esg-action-performance-check@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          iterations: 5
          minimum-desktop-score: 90
          minimum-mobile-score: 60
          urls: |
            http://localhost:3000/courses?search=maths

      - name: Upload performance reports as artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: ./reports
